# Site settings
title: "مریم اکبری"
#motto: "در مورد نرم‌افزار و ایده‌هایم"
author: Mehdi Sadeghi
email: sadeghi@mehdix.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mehdix.ir" # the base hostname & protocol for your site
keywords: "کامپیوتر، برنامه‌نویسی، پایتون، علم"
copyright: "Commons Attribution 4.0 International"
robot: ""
description: > # this means to ignore newlines until "baseurl:"
  سکوی انتشار مطالبی در مورد دانش تولید نرم‌افزار و ایده‌ها و علایق شخصی‌ام.

long_description: >
متولد آبان ماه 1370، دانشجوی مهندسی نرم افزار، دانشگاه بیرجند

twitter_username: mehdisadeghii
github_username:  mehdisadeghi
fullname: "مهدی صادقی"
favicon: "img/favicon.png"


#outputting
permalink: :title.html

# Build settings
markdown: kramdown
kramdown:
    coderay_line_numbers: nil
encoding: utf-8
timezone: Europe/Berlin

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      author: "مهدی صادقی"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: "مهدی صادقی"

gems:
  - jekyll-sitemap
  - jalalidate
  - coderay

